version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Adjust the Node.js version as required
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running linting..."
      - npm run lint || echo "No lint script defined"
  build:
    commands:
      - echo "Running tests..."
      - npm test
      - echo "Building the application..."
      - npm run build || echo "No build script defined"
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
cache:
  paths:
    - node_modules/**/*
